name: PRs reviews reminder (self testing for MS Teams)

on: ["push", "pull_request"]

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: bitjoo/pr-reviews-reminder-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          webhook-url: "http://foobar.some/url" # Required
          provider: "slack" # Required (slack or msteams)
          channel: "" # Optional, eg: #general
          github-provider-map: "bitjoo:UAABCDEFG" # Optional, eg: "DavideViolante:UEABCDEFG,foobar:UAABCDEFG"
